import { AppFrame, EmptyState } from "@/components/app-frame";
import { prisma } from "@/src/db";
import { videoStageLabels, type VideoStageCode } from "@/src/domain/video-production";

export const dynamic = "force-dynamic";
const statusLabels: Record<string, string> = { PLANNING: "Planificación", IN_PROGRESS: "En producción", BLOCKED: "Bloqueada", IN_REVIEW: "En revisión", READY: "Lista", CANCELLED: "Cancelada" };

export default async function VideosPage() {
  let projects: any[] = [];
  try { projects = await prisma.videoProject.findMany({ where: { agentRunStatus: { not: "IDLE" } }, orderBy: { updatedAt: "desc" }, include: { outlet: true, contentVariant: { include: { trend: true } }, _count: { select: { tasks: true, evidences: true, comments: true } } } }); } catch {}
  return <AppFrame active="/videos" title="Producción AI" subtitle="Aquí aparecen únicamente las órdenes que ya entraron al trabajo conjunto del equipo">
    <div className="section-heading video-index-heading"><div><span className="eyebrow">02 · CENTRO DE PRODUCCIÓN</span><h2>Producciones en curso y terminadas</h2><p>Cada sala muestra actividad concurrente, producto en construcción y entregas individuales.</p></div><a className="secondary-button" href="/ordenes">← Ver órdenes</a></div>
    {projects.length ? <div className="video-project-grid">{projects.map((project) => { const isDocument = project.outputKind === "EDITORIAL_DOCUMENT"; const isGraphic = project.outputKind === "SOCIAL_CARD"; const displayHeadline = isGraphic && project.cardBaseText?.trim() ? project.cardBaseText : project.contentVariant.headline; const displayHook = isGraphic && project.cardAccentText?.trim() ? project.cardAccentText : project.objective ?? project.contentVariant.hook; return <a className={`panel video-project-card outlet-${project.outlet.slug} ${isDocument ? "document-project" : isGraphic ? "graphic-project" : ""}`} href={`/videos/${project.id}`} key={project.id}>
      <div className="project-preview"><div className="preview-status"><span><i/> {project.outlet.name}</span><b>{isDocument ? `PDF · ${project.pageSize ?? "Carta"}` : isGraphic ? `HTML · ${project.aspectRatio ?? "1:1"}` : project.aspectRatio ?? "16:9"}</b></div><div><small>{project.productType ?? (isDocument ? "Documento editorial" : isGraphic ? "Tarjeta gráfica social" : "Producto audiovisual")}</small><strong>{isGraphic ? displayHeadline : project.contentVariant.trend.title}</strong><span className="preview-play">{isDocument ? "PDF" : isGraphic ? "HTML" : "▶"}</span></div><div className="preview-time"><span><i style={{ width: `${project.progress}%` }}/></span><time>{isDocument || isGraphic ? `${project.progress}%` : `${project.durationSeconds ?? 60}s`}</time></div></div>
      <div className="video-card-body"><div className="video-project-head"><span>{project.primaryPlatform ?? "Destino por definir"}</span><span className={`badge badge-${project.status === "BLOCKED" ? "red" : project.status === "READY" ? "green" : "blue"}`}>{statusLabels[project.status] ?? project.status}</span></div><h3>{displayHeadline}</h3><p>{displayHook}</p><div className="video-spec-row">{isDocument ? <><span>{project.pageSize ?? "Carta"}</span><span>{project.documentStyle ?? "Nota informativa"}</span><span>Documento PDF</span></> : isGraphic ? <><span>{project.aspectRatio ?? "1:1"}</span><span>HTML editable</span><span>Exportación PNG</span></> : <><span>{project.resolution ?? "1080p"}</span><span>{project.captionStyle ?? "Subtítulos"}</span><span>{project.voiceStyle ?? "Voz informativa"}</span></>}</div><div className="video-progress"><span><i style={{ width: `${project.progress}%` }}/></span><b>{project.progress}%</b></div><div className="video-project-meta"><span>Etapa: {videoStageLabels[project.currentStage as VideoStageCode]}</span><span>{project._count.tasks} agentes · {project._count.evidences} entregas</span></div><div className="open-control-room">Abrir sala de control <span>→</span></div></div>
    </a>; })}</div> : <EmptyState title="Todavía no hay producciones activas" detail="Completa y envía una orden; en ese momento aparecerá aquí con los nueve autores AI trabajando."/>}
  </AppFrame>;
}
