import { prisma } from "@/src/db";
import { calculateTrendScore } from "@/src/domain/scoring";
import { assertTransition, type WorkflowStatus } from "@/src/domain/state-machine";
import { evaluateEvidence } from "@/src/domain/evidence";
import { classifyEditorialRisk, maxRisk, type RiskLevel } from "@/src/domain/risk";
import { createOpenAIAdapter } from "@/src/adapters/openai";
import { createNotionAdapter, type NotionTaskPayload } from "@/src/adapters/notion";
import { redactSecrets } from "@/src/security/urls";

export type WorkflowStreamEvent = { status: WorkflowStatus; reason: string; progress: number; createdAt: string };
const workflowProgress: Record<WorkflowStatus, number> = { DETECTED: 0, SCORING: 8, SCORED: 16, INVESTIGATING: 30, EVIDENCE_INCOMPLETE: 44, EVIDENCE_READY: 48, GENERATING_VARIANTS: 62, DRAFTS_READY: 82, SYNCING_NOTION: 90, AWAITING_APPROVAL: 100, APPROVED: 100, REJECTED: 100, NEEDS_REVISION: 70, FAILED: 0, CANCELLED: 0 };

export async function transitionRun(workflowRunId: string, to: WorkflowStatus, actor: { type: "USER" | "AGENT" | "SYSTEM"; id?: string; userId?: string }, reason: string, metadata?: Record<string, unknown>) {
  return prisma.$transaction(async (tx) => { const run = await tx.workflowRun.findUniqueOrThrow({ where: { id: workflowRunId } }); const from = run.status as WorkflowStatus; assertTransition(from, to); await tx.workflowEvent.create({ data: { workflowRunId, fromStatus: from, toStatus: to, actorType: actor.type, actorId: actor.id, userId: actor.userId, reason, metadata: metadata ? redactSecrets(metadata) as object : undefined } }); await tx.workflowRun.update({ where: { id: workflowRunId }, data: { status: to, lastError: to === "FAILED" ? reason : null, completedAt: ["APPROVED", "REJECTED", "CANCELLED"].includes(to) ? new Date() : undefined } }); await tx.trend.update({ where: { id: run.trendId }, data: { status: to } }); });
}

export async function enqueueWorkflow(trendId: string) {
  const key = `editorial:${trendId}`; const run = await prisma.workflowRun.upsert({ where: { idempotencyKey: key }, create: { trendId, idempotencyKey: key }, update: {} });
  await prisma.job.upsert({ where: { idempotencyKey: `workflow:${run.id}` }, create: { type: "EDITORIAL_WORKFLOW", payload: { workflowRunId: run.id }, idempotencyKey: `workflow:${run.id}` }, update: { status: "PENDING", availableAt: new Date(), lastError: null } }); return run;
}

function scoreInputs(trend: { observedReach: number | null; sourceName: string | null; title: string }, sourceCount: number) { const guatemala = /guatemala|guate|quetzaltenango|sacatepéquez|petén|congreso|transmetro/i.test(trend.title) ? 95 : 55; return { velocity: Math.min(100, 45 + Math.round(Math.log10(Math.max(1, trend.observedReach ?? 10)) * 18)), recurrence: Math.min(100, 25 + sourceCount * 22), sourceQuality: Math.min(100, 30 + sourceCount * 25 + (trend.sourceName ? 10 : 0)), guatemalaRelevance: guatemala, evidence: { observedReach: trend.observedReach, sourceCount, titleMatch: guatemala === 95 } }; }

export async function processWorkflowRun(workflowRunId: string, emit?: (event: WorkflowStreamEvent) => void | Promise<void>) {
  const run = await prisma.workflowRun.findUniqueOrThrow({ where: { id: workflowRunId }, include: { trend: { include: { sources: true } } } });
  const advance = async (to: WorkflowStatus, actor: { type: "USER" | "AGENT" | "SYSTEM"; id?: string; userId?: string }, reason: string, metadata?: Record<string, unknown>) => {
    await transitionRun(run.id, to, actor, reason, metadata);
    await emit?.({ status: to, reason, progress: workflowProgress[to], createdAt: new Date().toISOString() });
  };
  try {
    if (run.status === "DETECTED" || run.status === "FAILED") { await advance("SCORING", { type: "SYSTEM", id: "deterministic-scorer" }, "Métrica está calculando relevancia, velocidad y calidad de fuente"); const score = calculateTrendScore(scoreInputs(run.trend, run.trend.sources.length)); await prisma.trendScore.create({ data: { trendId: run.trendId, total: score.total, velocity: score.partials.velocity, recurrence: score.partials.recurrence, sourceQuality: score.partials.sourceQuality, guatemalaRelevance: score.partials.guatemalaRelevance, evidence: score.evidence as object, explanation: score.explanation, formulaVersion: score.formulaVersion } }); await advance("SCORED", { type: "SYSTEM", id: "deterministic-scorer" }, score.explanation); }
    const current = await prisma.workflowRun.findUniqueOrThrow({ where: { id: run.id } });
    if (current.status === "SCORED" || current.status === "EVIDENCE_INCOMPLETE") await advance("INVESTIGATING", { type: "AGENT", id: "orchestrator-v1" }, "Certeza AI investiga las fuentes mientras Tinta y Lumen preparan los cuatro enfoques");
    else return current;
    const profiles = await prisma.editorialProfileVersion.findMany({ where: { profile: { outlet: { active: true } } }, orderBy: { version: "desc" }, distinct: ["profileId"], include: { profile: { include: { outlet: true } } } });
    const agent = createOpenAIAdapter(); const started = Date.now(); const result = await agent.runEditorialWorkflow({ title: run.trend.title, description: run.trend.description ?? undefined, sources: run.trend.sources.map((source) => ({ id: source.id, title: source.title, url: source.url, domain: source.domain, excerpt: source.excerpt, isPrimary: source.isPrimary })), profiles: profiles.map((profile) => ({ slug: profile.profile.outlet.slug, focus: profile.focus as string[], tone: profile.tone as string[], limits: profile.limits as string[] })) }, async (stage) => {
      const outletActivity: Record<string, string> = {
        "variant:insonimio-guatemala": "Tinta redacta la tarjeta de Insomnio Guatemala y Lumen define su jerarquía visual",
        "variant:yo-amo-guate": "Tinta adapta la historia para Yo Amo Guate y Lumen selecciona el formato social",
        "variant:trece-noticias": "Tinta construye la nota de prensa de Trece Noticias con sus fuentes visibles",
        "variant:tv-azteca-guate": "Tinta prepara el guion para TV Azteca Guate y Lumen ordena los apoyos audiovisuales",
      };
      const isVariantStage = stage === "variants" || stage.startsWith("variant:");
      await emit?.({ status: isVariantStage ? "GENERATING_VARIANTS" : "INVESTIGATING", reason: outletActivity[stage] ?? (isVariantStage ? "Tinta redacta mientras Lumen define formatos, jerarquía y enfoque visual" : "Certeza AI está contrastando el expediente y separando hechos de afirmaciones"), progress: isVariantStage ? 58 : 30, createdAt: new Date().toISOString() });
    });
    const investigation = await prisma.investigation.create({ data: { trendId: run.trendId, summary: result.investigation.summary, mainQuestion: result.investigation.mainQuestion, unconfirmedClaims: result.investigation.unconfirmedClaims, relevantDates: result.investigation.relevantDates, people: result.investigation.people, organizations: result.investigation.organizations, places: result.investigation.places, figures: result.investigation.figures, editorialRisks: result.investigation.editorialRisks, confidence: result.investigation.confidence, verdict: result.investigation.verdict, opinion: result.investigation.opinion } });
    for (const fact of result.investigation.confirmedFacts) for (const sourceId of fact.sourceIds.filter((id) => run.trend.sources.some((source) => source.id === id))) await prisma.evidenceItem.create({ data: { investigationId: investigation.id, sourceId, claim: fact.claim, confidence: fact.confidence, confirmed: true } });
    for (const contradiction of result.investigation.contradictions) await prisma.contradiction.create({ data: { investigationId: investigation.id, description: contradiction.description, sourceIds: contradiction.sourceIds, severity: contradiction.severity } });
    await prisma.agentTrace.create({ data: { workflowRunId: run.id, agent: "orchestrator/research", model: result.model, promptVersion: "editorial-v1", tools: ["investigar_expediente", "crear_versiones_editoriales"], parameters: redactSecrets({ sourceCount: run.trend.sources.length }) as object, result: redactSecrets(result.investigation) as object, durationMs: result.durationMs || Date.now() - started, inputTokens: result.usage?.inputTokens, outputTokens: result.usage?.outputTokens, finalStatus: "COMPLETED", sourceIds: run.trend.sources.map((source) => source.id) } });
    const evidence = evaluateEvidence(run.trend.sources.map((source) => ({ id: source.id, domain: source.domain, isPrimary: source.isPrimary, accessible: source.accessStatus === "ACCESSIBLE" })), result.investigation.confirmedFacts.length);
    const evidenceLimited = !evidence.ready || ["INCOMPLETE", "DOUBTFUL", "NOT_PUBLISHABLE"].includes(result.investigation.verdict);
    if (evidenceLimited) { await advance("EVIDENCE_INCOMPLETE", { type: "AGENT", id: "research-specialist-v1" }, evidence.reasons.join(" ") || result.investigation.opinion); await advance("GENERATING_VARIANTS", { type: "AGENT", id: "orchestrator-v1" }, "Tinta redacta borradores preventivos, claramente marcados como no publicables hasta sumar fuentes"); }
    else { await advance("EVIDENCE_READY", { type: "AGENT", id: "research-specialist-v1" }, "Expediente con fuente primaria, dos dominios independientes y hechos respaldados"); await advance("GENERATING_VARIANTS", { type: "AGENT", id: "orchestrator-v1" }, "Tinta y Lumen adaptan la historia para los cuatro medios"); }
    const outlets = await prisma.outlet.findMany({ where: { active: true } }); let aggregateRisk: RiskLevel = evidenceLimited ? "CRITICAL" : "LOW";
    for (const variant of result.variants) { const outlet = outlets.find((item) => item.slug === variant.outletSlug); if (!outlet) throw new Error(`Medio no configurado: ${variant.outletSlug}`); const ruleRisk = classifyEditorialRisk({ title: variant.headline, body: `${variant.body} ${result.investigation.editorialRisks.join(" ")}`, suggested: evidenceLimited ? "CRITICAL" : variant.suggestedRisk }); aggregateRisk = maxRisk(aggregateRisk, ruleRisk.level); const evidenceWarning = evidenceLimited ? ["BORRADOR PREVENTIVO: evidencia insuficiente; no publicar hasta completar la verificación."] : []; await prisma.contentVariant.upsert({ where: { workflowRunId_outletId_version: { workflowRunId: run.id, outletId: outlet.id, version: 1 } }, create: { trendId: run.trendId, workflowRunId: run.id, outletId: outlet.id, headline: variant.headline, hook: variant.hook, angle: variant.angle, socialCaption: variant.socialCaption, body: variant.body, recommendedFormat: variant.recommendedFormat, callToAction: variant.callToAction, sourceIds: variant.sourceIds, factIds: variant.factIds, confidence: variant.confidence, riskLevel: ruleRisk.level, warnings: [...evidenceWarning, ...variant.warnings, ruleRisk.explanation], reviewClaims: variant.reviewClaims, status: "NEEDS_REVIEW" }, update: { headline: variant.headline, hook: variant.hook, angle: variant.angle, socialCaption: variant.socialCaption, body: variant.body, recommendedFormat: variant.recommendedFormat, callToAction: variant.callToAction, sourceIds: variant.sourceIds, factIds: variant.factIds, confidence: variant.confidence, riskLevel: ruleRisk.level, warnings: [...evidenceWarning, ...variant.warnings, ruleRisk.explanation], reviewClaims: variant.reviewClaims } }); }
    await advance("DRAFTS_READY", { type: "AGENT", id: "adaptation-specialist-v1" }, evidenceLimited ? "Cuatro borradores listos con alerta de evidencia incompleta" : "Cuatro versiones diferenciadas validadas contra el expediente"); await advance("SYNCING_NOTION", { type: "SYSTEM", id: "notion-adapter" }, "Nexo registra el paquete editorial y prepara el control humano");
    const score = await prisma.trendScore.findFirstOrThrow({ where: { trendId: run.trendId }, orderBy: { calculatedAt: "desc" } }); const variants = await prisma.contentVariant.findMany({ where: { workflowRunId: run.id }, include: { outlet: true } }); const contradictions = await prisma.contradiction.findMany({ where: { investigationId: investigation.id } });
    const notionPayload: NotionTaskPayload = { workflowId: run.id, title: run.trend.title, score: score.total, status: "AWAITING_APPROVAL", investigationSummary: investigation.summary, confidence: investigation.confidence, risk: aggregateRisk, sourceLinks: run.trend.sources.map((source) => source.url), contradictions: contradictions.map((item) => item.description), variants: variants.map((variant) => ({ outlet: variant.outlet.name, headline: variant.headline, body: variant.body })), createdAt: new Date().toISOString(), dossierUrl: `${process.env.APP_URL ?? "http://localhost:3000"}/expedientes/${run.trendId}` };
    const notion = createNotionAdapter(); const notionResult = await notion.syncTask(notionPayload); await prisma.notionSync.upsert({ where: { workflowRunId: run.id }, create: { workflowRunId: run.id, idempotencyKey: `notion:${run.id}`, externalPageId: notionResult.externalPageId, externalUrl: notionResult.externalUrl, status: notionResult.mocked ? "EXCEPTION" : "SYNCED", payload: notionPayload as object, attemptCount: 1, syncedAt: new Date() }, update: { externalPageId: notionResult.externalPageId, externalUrl: notionResult.externalUrl, status: notionResult.mocked ? "EXCEPTION" : "SYNCED", payload: notionPayload as object, attemptCount: { increment: 1 }, lastError: null, syncedAt: new Date() } }); await prisma.integrationEvent.upsert({ where: { idempotencyKey: `notion:${run.id}` }, create: { integration: "NOTION", action: "CREATE_TASK", idempotencyKey: `notion:${run.id}`, request: redactSecrets(notionPayload) as object, response: redactSecrets(notionResult) as object, success: true }, update: { response: redactSecrets(notionResult) as object, success: true, error: null } });
    await advance("AWAITING_APPROVAL", { type: "SYSTEM", id: "notion-adapter" }, notionResult.mocked ? "Paquete conservado localmente; la revisión humana ya está disponible" : "Tarea sincronizada con Notion", { notionPageId: notionResult.externalPageId, mocked: notionResult.mocked }); return prisma.workflowRun.findUniqueOrThrow({ where: { id: run.id } });
  } catch (error) { const latest = await prisma.workflowRun.findUnique({ where: { id: run.id } }); if (latest && latest.status !== "FAILED" && !["APPROVED", "REJECTED", "CANCELLED"].includes(latest.status)) await advance("FAILED", { type: "SYSTEM", id: "worker" }, error instanceof Error ? error.message : "Error desconocido"); throw error; }
}
