import { AppFrame, EmptyState } from "@/components/app-frame";
import { prisma } from "@/src/db";

export const dynamic = "force-dynamic";
export default async function RadarPage() {
  let trends: Awaited<ReturnType<typeof prisma.trend.findMany>> & never[] = [] as never;
  try { trends = await prisma.trend.findMany({ where: { deletedAt: null }, orderBy: { createdAt: "desc" }, include: { scores: { orderBy: { calculatedAt: "desc" }, take: 1 }, suggestedOutlet: true, sources: true } }) as never; } catch { trends = [] as never; }
  return <AppFrame active="/radar" title="Radar de tendencias" subtitle="Señales normalizadas, puntuadas y listas para investigar" actions={<a className="primary-button" href="/radar/nueva">＋ Nueva tendencia</a>}><div className="toolbar"><input aria-label="Buscar tendencias" placeholder="Buscar por título o fuente…" /><select aria-label="Estado"><option>Todos los estados</option><option>Detectadas</option><option>Evidencia lista</option></select><select aria-label="Medio"><option>Todos los medios</option><option>Insonimio Guatemala</option><option>Yo Amo Guate</option><option>Trece Noticias</option><option>TV Azteca Guate</option></select></div><article className="panel data-panel">{trends.length ? <table><thead><tr><th>Tendencia</th><th>Puntuación</th><th>Medio sugerido</th><th>Estado</th><th>Fuentes</th><th /></tr></thead><tbody>{trends.map((trend: any) => <tr key={trend.id}><td><a href={`/expedientes/${trend.id}`}>{trend.title}</a><small>{trend.isFictional ? "Dato ficticio de demostración" : trend.sourceName ?? "Entrada manual"}</small></td><td><strong className="large-score">{trend.scores[0]?.total ?? "—"}</strong><small>{trend.scores[0]?.formulaVersion ?? "Pendiente"}</small></td><td><span className="badge badge-blue">{trend.suggestedOutlet?.name ?? "Por definir"}</span></td><td><span className="badge badge-amber">{trend.status}</span></td><td>{trend.sources.length}</td><td><form action={`/api/workflows`} method="post"><input type="hidden" name="trendId" value={trend.id}/><button className="text-button">Procesar →</button></form></td></tr>)}</tbody></table> : <EmptyState title="No hay tendencias almacenadas" detail="Crea una entrada manual o procesa un feed RSS para comenzar." />}</article></AppFrame>;
}
