import { NextResponse } from "next/server";
import { z } from "zod";
import { requireUser } from "@/src/auth";
import { prisma } from "@/src/db";
import { validateApproval } from "@/src/domain/permissions";
import { transitionRun } from "@/src/services/workflow";
import type { RiskLevel } from "@/src/domain/risk";
import { apiError, protectMutation } from "@/src/security/http";
const schema = z.object({ action: z.enum(["APPROVE", "REJECT", "REQUEST_CHANGES"]), comment: z.string().max(4000).optional(), confirmed: z.boolean().optional() });
const order: RiskLevel[] = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { const blocked = protectMutation(request, "approval", 20); if (blocked) return blocked; try { const user = await requireUser(); const { id } = await params; const input = schema.parse(await request.json()); const run = await prisma.workflowRun.findUniqueOrThrow({ where: { id }, include: { variants: { include: { outlet: true } } } }); if (run.status !== "AWAITING_APPROVAL") throw new Error("El flujo no está pendiente de aprobación."); const risk = run.variants.reduce<RiskLevel>((max, variant) => order.indexOf(variant.riskLevel as RiskLevel) > order.indexOf(max) ? variant.riskLevel as RiskLevel : max, "LOW"); const sameOutlet = !user.outletId || run.variants.every((variant) => variant.outletId === user.outletId); if (input.action === "APPROVE") validateApproval({ role: user.roleCode, risk, comment: input.comment, confirmed: input.confirmed, sameOutlet }); else if (!["ADMIN", "DIRECCION", "EDITOR_SENIOR", "EDITOR_MARCA"].includes(user.roleCode)) throw new Error("El usuario no tiene permiso para decidir sobre contenidos."); const before = run.variants.map((variant) => ({ id: variant.id, headline: variant.headline, body: variant.body, status: variant.status })); await prisma.$transaction(async (tx) => { await tx.approval.create({ data: { workflowRunId: id, userId: user.id, action: input.action, comment: input.comment, contentBefore: before, riskAtDecision: risk, confirmed: Boolean(input.confirmed) } }); await tx.contentVariant.updateMany({ where: { workflowRunId: id }, data: { status: input.action === "APPROVE" ? "APPROVED" : input.action === "REJECT" ? "REJECTED" : "NEEDS_REVISION" } }); }); const target = input.action === "APPROVE" ? "APPROVED" : input.action === "REJECT" ? "REJECTED" : "NEEDS_REVISION"; await transitionRun(id, target, { type: "USER", id: user.email, userId: user.id }, input.comment || `Decisión humana: ${input.action}`); return NextResponse.json({ status: target }); } catch (error) { return apiError(error); } }
