import "dotenv/config";
import { prisma } from "../src/db";
import { makeDedupeKey, normalizeTitle } from "../src/domain/dedupe";
import { videoTaskBlueprints } from "../src/domain/video-production";

const profileData = [
  { slug: "insonimio-guatemala", name: "Insonimio Guatemala", focus: ["Tendencias", "Cultura digital", "Entretenimiento", "Conversación social", "Temas virales"], tone: ["Cercano", "Conversacional", "Curioso", "Directo"], limits: ["No inventar controversias", "No afirmar rumores como hechos", "No exagerar cifras", "No usar morbo con víctimas"] },
  { slug: "yo-amo-guate", name: "Yo Amo Guate", focus: ["Identidad guatemalteca", "Turismo", "Cultura", "Comunidades", "Tradiciones", "Información útil"], tone: ["Positivo", "Cercano", "Humano", "Culturalmente respetuoso"], limits: ["No presentar publicidad como noticia", "No generalizar identidades", "Verificar topónimos", "No ocultar hechos relevantes"] },
  { slug: "trece-noticias", name: "Trece Noticias", focus: ["Actualidad", "Política", "Economía", "Seguridad", "Servicios", "Información pública"], tone: ["Informativo", "Claro", "Neutral", "Preciso"], limits: ["No publicar acusaciones sin atribución", "No omitir certeza", "Priorizar fuentes primarias", "Marcar contenido sensible"] },
  { slug: "tv-azteca-guate", name: "TV Azteca Guate", focus: ["Noticias audiovisuales", "Actualidad de alto impacto", "Servicio", "Entretenimiento", "Cobertura nacional"], tone: ["Ágil", "Televisivo", "Claro", "Enérgico", "Responsable"], limits: ["No dramatizar hechos sensibles", "No usar imágenes fuera de contexto", "Atribuir material audiovisual", "Diferenciar avances de información confirmada"] },
];

async function main() {
  const rolePermissions: Record<string, string[]> = { ADMIN: ["*"], DIRECCION: ["read", "critical:manage", "content:approve"], EDITOR_SENIOR: ["read", "draft:edit", "content:approve"], EDITOR_MARCA: ["read", "draft:edit", "content:approve:own"], REPORTERO: ["read", "trend:create", "source:add"], LECTOR: ["read"] };
  const roles = new Map<string, string>();
  for (const [code, permissions] of Object.entries(rolePermissions)) { const role = await prisma.role.upsert({ where: { code }, create: { code, name: code.replaceAll("_", " "), permissions }, update: { permissions } }); roles.set(code, role.id); }
  const outlets = new Map<string, { id: string; name: string }>();
  for (const item of profileData) { const outlet = await prisma.outlet.upsert({ where: { slug: item.slug }, create: { slug: item.slug, name: item.name }, update: { name: item.name, active: true } }); outlets.set(item.slug, outlet); const profile = await prisma.editorialProfile.upsert({ where: { outletId: outlet.id }, create: { outletId: outlet.id }, update: {} }); await prisma.editorialProfileVersion.upsert({ where: { profileId_version: { profileId: profile.id, version: 1 } }, create: { profileId: profile.id, version: 1, focus: item.focus, tone: item.tone, limits: item.limits, prompt: `Perfil editorial inicial de ${item.name}. Aplicar foco, tono y límites sin alterar hechos.` }, update: { focus: item.focus, tone: item.tone, limits: item.limits } }); }
  const users = [
    { email: "admin@nexo.demo", name: "Administrador Nexo", role: "ADMIN", outlet: null },
    { email: "ana@nexo.demo", name: "Ana Morales", role: "EDITOR_SENIOR", outlet: null },
    { email: "luis@nexo.demo", name: "Luis Pérez", role: "EDITOR_MARCA", outlet: "insonimio-guatemala" },
    { email: "sofia@nexo.demo", name: "Sofía López", role: "REPORTERO", outlet: "trece-noticias" },
    { email: "direccion@nexo.demo", name: "Dirección Editorial", role: "DIRECCION", outlet: null },
    { email: "maria@nexo.demo", name: "María Castellanos", role: "EDITOR_MARCA", outlet: "tv-azteca-guate" },
  ];
  for (const user of users) await prisma.user.upsert({ where: { email: user.email }, create: { email: user.email, name: user.name, roleId: roles.get(user.role)!, outletId: user.outlet ? outlets.get(user.outlet)!.id : null }, update: { name: user.name, roleId: roles.get(user.role)!, outletId: user.outlet ? outlets.get(user.outlet)!.id : null, active: true } });
  const feeds = [
    ["INGUAT Noticias", "https://inguat.gob.gt/feed", "Turismo", "OFFICIAL", 90], ["Congreso de Guatemala", "https://www.congreso.gob.gt/noticias/feed", "Política", "OFFICIAL", 95], ["Municipalidad de Guatemala", "https://www.muniguate.com/feed", "Servicios", "OFFICIAL", 88], ["Prensa Libre", "https://www.prensalibre.com/feed/", "Noticias", "MEDIA", 82], ["La Hora", "https://lahora.gt/feed/", "Noticias", "MEDIA", 80],
  ] as const;
  for (const [name, url, category, sourceType, trustLevel] of feeds) await prisma.rssFeed.upsert({ where: { url }, create: { name, url, category, sourceType, trustLevel }, update: { name, category, sourceType, trustLevel } });

  const cases = [
    { key: "culture", title: "Festival ficticio de barriletes presenta una ruta cultural comunitaria", description: "Caso ficticio para demostrar un tema cultural con evidencia suficiente.", outlet: "yo-amo-guate", status: "APPROVED", risk: "LOW", verdict: "CONFIRMED", confidence: 92, sources: [{ title: "Comunicado ficticio del comité organizador", url: "https://example.org/demo/barriletes-comunicado", domain: "example.org", primary: true }, { title: "Cobertura cultural ficticia independiente", url: "https://example.net/demo/barriletes-cultura", domain: "example.net", primary: false }] },
    { key: "service", title: "Cambio ficticio de horarios en una ruta urbana de Guatemala", description: "Caso ficticio de información de servicio pendiente de aprobación.", outlet: "trece-noticias", status: "AWAITING_APPROVAL", risk: "MEDIUM", verdict: "CONFIRMED", confidence: 88, sources: [{ title: "Aviso oficial ficticio", url: "https://example.org/demo/horarios-oficial", domain: "example.org", primary: true }, { title: "Verificación comunitaria ficticia", url: "https://example.net/demo/horarios-verificacion", domain: "example.net", primary: false }] },
    { key: "politics", title: "Propuesta legislativa ficticia sobre presupuesto público", description: "Caso ficticio de riesgo alto rechazado por falta de contexto suficiente.", outlet: "trece-noticias", status: "REJECTED", risk: "HIGH", verdict: "PARTIALLY_CONFIRMED", confidence: 74, sources: [{ title: "Iniciativa ficticia", url: "https://example.org/demo/iniciativa", domain: "example.org", primary: true }, { title: "Análisis ficticio independiente", url: "https://example.net/demo/analisis", domain: "example.net", primary: false }] },
    { key: "incomplete", title: "Rumor ficticio sobre cierre de un sitio turístico", description: "Caso ficticio con una sola fuente y evidencia insuficiente.", outlet: "insonimio-guatemala", status: "EVIDENCE_INCOMPLETE", risk: "MEDIUM", verdict: "INCOMPLETE", confidence: 42, sources: [{ title: "Publicación comunitaria ficticia", url: "https://example.com/demo/rumor", domain: "example.com", primary: false }] },
  ] as const;

  for (const item of cases) {
    const trend = await prisma.trend.upsert({ where: { dedupeKey: makeDedupeKey(item.title) }, create: { title: item.title, normalizedTitle: normalizeTitle(item.title), description: item.description, suggestedOutletId: outlets.get(item.outlet)!.id, status: item.status, dedupeKey: makeDedupeKey(item.title), isFictional: true, observedReach: item.key === "politics" ? 5800 : 1800 }, update: { status: item.status, isFictional: true } });
    const sourceRows = [];
    for (const source of item.sources) sourceRows.push(await prisma.trendSource.upsert({ where: { trendId_url: { trendId: trend.id, url: source.url } }, create: { trendId: trend.id, title: source.title, url: source.url, domain: source.domain, sourceType: source.primary ? "OFFICIAL" : "MEDIA", excerpt: `${item.description} Evidencia ficticia, no utilizar como información real.`, confidence: source.primary ? 95 : 78, isPrimary: source.primary }, update: {} }));
    if (!(await prisma.trendScore.findFirst({ where: { trendId: trend.id } }))) await prisma.trendScore.create({ data: { trendId: trend.id, total: item.key === "culture" ? 88 : item.key === "service" ? 82 : item.key === "politics" ? 71 : 53, velocity: 72, recurrence: 68, sourceQuality: item.sources.length > 1 ? 90 : 35, guatemalaRelevance: 95, evidence: { fixture: true }, explanation: "Puntuación ficticia calculada con la fórmula determinista v1.", formulaVersion: "1.0.0" } });
    let investigation = await prisma.investigation.findUnique({ where: { trendId_version: { trendId: trend.id, version: 1 } } });
    if (!investigation) investigation = await prisma.investigation.create({ data: { trendId: trend.id, summary: item.description, mainQuestion: `¿Qué está confirmado sobre ${item.title}?`, unconfirmedClaims: item.verdict === "INCOMPLETE" ? ["El cierre no fue confirmado"] : [], relevantDates: [], people: [], organizations: [], places: ["Guatemala"], figures: [], editorialRisks: [item.risk], confidence: item.confidence, verdict: item.verdict, opinion: item.verdict === "INCOMPLETE" ? "Se requiere una segunda fuente y una fuente primaria." : "Expediente de demostración utilizable con revisión humana." } });
    for (const [index, source] of sourceRows.entries()) await prisma.evidenceItem.upsert({ where: { investigationId_sourceId_claim: { investigationId: investigation.id, sourceId: source.id, claim: `Hecho ficticio ${index + 1} relacionado con ${item.title}` } }, create: { investigationId: investigation.id, sourceId: source.id, claim: `Hecho ficticio ${index + 1} relacionado con ${item.title}`, confidence: source.confidence }, update: {} });
    const run = await prisma.workflowRun.upsert({ where: { idempotencyKey: `seed:${item.key}` }, create: { trendId: trend.id, idempotencyKey: `seed:${item.key}`, status: item.status, completedAt: ["APPROVED", "REJECTED"].includes(item.status) ? new Date() : null }, update: { status: item.status } });
    if (!(await prisma.workflowEvent.findFirst({ where: { workflowRunId: run.id } }))) await prisma.workflowEvent.create({ data: { workflowRunId: run.id, toStatus: item.status, actorType: "SYSTEM", actorId: "seed", reason: "Estado ficticio cargado para demostración" } });
    if (item.status !== "EVIDENCE_INCOMPLETE") for (const outlet of profileData) await prisma.contentVariant.upsert({ where: { workflowRunId_outletId_version: { workflowRunId: run.id, outletId: outlets.get(outlet.slug)!.id, version: 1 } }, create: { trendId: trend.id, workflowRunId: run.id, outletId: outlets.get(outlet.slug)!.id, headline: `${outlet.name}: ${item.title}`, hook: `Entrada ficticia adaptada para ${outlet.name}.`, angle: outlet.focus[0], socialCaption: `Borrador ficticio: ${item.title}.`, body: `${item.description} Este contenido es un fixture de demostración y conserva el mismo núcleo factual.`, recommendedFormat: outlet.slug === "tv-azteca-guate" ? "Video explicativo" : outlet.slug === "trece-noticias" ? "Nota web" : "Carrusel", callToAction: "Revisar fuentes antes de cerrar.", sourceIds: sourceRows.map((source) => source.id), factIds: sourceRows.map((_, index) => `fact-${index + 1}`), confidence: item.confidence, riskLevel: item.risk, warnings: ["Contenido ficticio"], reviewClaims: [], status: item.status === "APPROVED" ? "APPROVED" : item.status === "REJECTED" ? "REJECTED" : "NEEDS_REVIEW" }, update: {} });
    if (item.key === "service") {
      const videoVariant = await prisma.contentVariant.findUniqueOrThrow({ where: { workflowRunId_outletId_version: { workflowRunId: run.id, outletId: outlets.get("tv-azteca-guate")!.id, version: 1 } } });
      const brief = { outputKind: "AUDIOVISUAL", productType: "Video explicativo de servicio", objective: "Explicar con claridad el cambio ficticio de horarios y qué debe comprobar la audiencia antes de viajar.", audience: "Usuarios del transporte urbano en Guatemala", durationSeconds: 60, primaryPlatform: "Sitio web / TV", productionNotes: "Entregar master horizontal, adaptación vertical, subtítulos y rótulos de fuentes. Mantener visible que el caso es ficticio.", aspectRatio: "16:9", resolution: "1080p", captionStyle: "Informativos", voiceStyle: "Informativa", pageSize: "Carta", documentStyle: "Nota informativa" };
      const project = await prisma.videoProject.upsert({ where: { contentVariantId: videoVariant.id }, create: { contentVariantId: videoVariant.id, workflowRunId: run.id, outletId: videoVariant.outletId, title: `TV Azteca Guate · ${videoVariant.headline}`, status: "IN_PROGRESS", currentStage: "SCRIPT", progress: 25, ...brief }, update: { title: `TV Azteca Guate · ${videoVariant.headline}`, ...brief } });
      const collaborators = await prisma.user.findMany({ where: { email: { in: ["admin@nexo.demo", "sofia@nexo.demo", "maria@nexo.demo", "ana@nexo.demo", "direccion@nexo.demo"] } }, include: { role: true } });
      const responsibilities: Record<string, string> = { ADMIN: "Observa al equipo AI, controla puntos críticos y decide al final", REPORTERO: "Brief, verificación y registro de producción", EDITOR_MARCA: "Guion, plan visual y edición de marca", EDITOR_SENIOR: "Control factual, de riesgo y calidad editorial", DIRECCION: "Decisión y visto bueno final" };
      for (const collaborator of collaborators) await prisma.videoParticipant.upsert({ where: { videoProjectId_userId: { videoProjectId: project.id, userId: collaborator.id } }, create: { videoProjectId: project.id, userId: collaborator.id, responsibility: responsibilities[collaborator.role.code] }, update: { responsibility: responsibilities[collaborator.role.code] } });
      const byRole = new Map(collaborators.map((collaborator) => [collaborator.role.code, collaborator.id]));
      for (const task of videoTaskBlueprints) await prisma.videoTask.upsert({ where: { videoProjectId_order: { videoProjectId: project.id, order: task.order } }, create: { videoProjectId: project.id, ...task, assigneeId: byRole.get(task.assignedRole), status: task.order <= 2 ? "DONE" : task.order === 3 ? "IN_PROGRESS" : "PENDING", deliverable: task.order === 1 ? "Brief de 60 segundos y audiencia general definido." : task.order === 2 ? "Dos fuentes revisadas; uso de material sujeto a créditos." : null, completedAt: task.order <= 2 ? new Date() : null }, update: { title: task.title, description: task.description, stage: task.stage, assignedRole: task.assignedRole, agentKey: task.agentKey, agentName: task.agentName } });
      if (await prisma.videoEvidence.count({ where: { videoProjectId: project.id } }) === 0) {
        const reportero = collaborators.find((collaborator) => collaborator.role.code === "REPORTERO")!;
        const factTask = await prisma.videoTask.findUniqueOrThrow({ where: { videoProjectId_order: { videoProjectId: project.id, order: 2 } } });
        await prisma.videoEvidence.createMany({ data: [{ videoProjectId: project.id, authorId: reportero.id, type: "STATUS_CHANGE", title: "Producción iniciada", description: "Se creó el tablero colaborativo de demostración." }, { videoProjectId: project.id, taskId: factTask.id, authorId: reportero.id, type: "CHECKLIST", title: "Verificación de fuentes completada", description: "Se revisaron las dos fuentes ficticias y las advertencias editoriales." }] });
      }
      if (await prisma.videoAgentActivity.count({ where: { videoProjectId: project.id } }) === 0) await prisma.videoAgentActivity.create({ data: { videoProjectId: project.id, agentKey: "nexo_orchestrator", agentName: "Nexo", agentRole: "Orquestador", action: "Sala preparada", detail: "El encargo está definido. Nueve autores AI esperan la orden del administrador.", status: "SYSTEM", progress: project.progress } });
      if (await prisma.videoComment.count({ where: { videoProjectId: project.id } }) === 0) await prisma.videoComment.create({ data: { videoProjectId: project.id, authorId: byRole.get("EDITOR_SENIOR")!, body: "El núcleo factual está listo. Mantengamos visible que el caso es ficticio y revisemos los rótulos antes del primer corte." } });
    }
    if (["AWAITING_APPROVAL", "APPROVED", "REJECTED"].includes(item.status)) await prisma.notionSync.upsert({ where: { workflowRunId: run.id }, create: { workflowRunId: run.id, idempotencyKey: `notion:seed:${item.key}`, externalPageId: `mock-seed-${item.key}`, status: "EXCEPTION", payload: { fixture: true, warning: "No se realizó una llamada real a Notion" }, syncedAt: new Date() }, update: {} });
  }
  console.log("Seed completado: todos los casos editoriales están marcados como ficticios.");
}

main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
