import { describe, expect, it } from "vitest";
import { MockOpenAIAdapter } from "@/src/adapters/openai";
import { MockNotionAdapter, type NotionAdapter } from "@/src/adapters/notion";
import { decideDemoApproval, executeDemoPipeline } from "@/src/services/demo-pipeline";

const complete = { title: "Actividad cultural ficticia en Guatemala", description: "Fixture", sources: [{ id: "s1", title: "Oficial", url: "https://a.example/1", domain: "a.example", excerpt: "La actividad está anunciada.", isPrimary: true }, { id: "s2", title: "Independiente", url: "https://b.example/2", domain: "b.example", excerpt: "La actividad fue confirmada de forma independiente.", isPrimary: false }], profiles: [{ slug: "insonimio-guatemala", focus: ["Tendencias"], tone: ["Cercano"], limits: [] }, { slug: "yo-amo-guate", focus: ["Cultura"], tone: ["Humano"], limits: [] }, { slug: "trece-noticias", focus: ["Actualidad"], tone: ["Neutral"], limits: [] }, { slug: "tv-azteca-guate", focus: ["Noticias audiovisuales"], tone: ["Ágil"], limits: [] }], score: { velocity: 80, recurrence: 70, sourceQuality: 90, guatemalaRelevance: 100, evidence: {} } };
describe("integración del flujo", () => {
  it("completa OpenAI y Notion simulados", async () => { const result = await executeDemoPipeline(complete, { openai: new MockOpenAIAdapter(), notion: new MockNotionAdapter() }); expect(result.history.at(-1)).toBe("AWAITING_APPROVAL"); expect(result.generated.variants).toHaveLength(4); expect(result.notion?.mocked).toBe(true); });
  it("se detiene con evidencia insuficiente", async () => { const result = await executeDemoPipeline({ ...complete, sources: complete.sources.slice(0, 1) }, { openai: new MockOpenAIAdapter(), notion: new MockNotionAdapter() }); expect(result.history.at(-1)).toBe("EVIDENCE_INCOMPLETE"); expect(result.notion).toBeNull(); });
  it("propaga fallo de Notion y permite reintentar con el mismo payload", async () => { let attempts = 0; const flaky: NotionAdapter = { async syncTask(payload) { attempts++; if (attempts === 1) throw new Error("Notion no disponible"); return { externalPageId: "retry-ok", mocked: true, payload }; } }; await expect(executeDemoPipeline(complete, { openai: new MockOpenAIAdapter(), notion: flaky })).rejects.toThrow("Notion"); const retried = await executeDemoPipeline(complete, { openai: new MockOpenAIAdapter(), notion: flaky }); expect(retried.notion?.externalPageId).toBe("retry-ok"); expect(attempts).toBe(2); });
  it("registra rechazo y solicitud de corrección como estados humanos", () => { expect(decideDemoApproval({ status: "AWAITING_APPROVAL", action: "REJECT", role: "EDITOR_MARCA", risk: "MEDIUM" })).toBe("REJECTED"); expect(decideDemoApproval({ status: "AWAITING_APPROVAL", action: "REQUEST_CHANGES", role: "EDITOR_SENIOR", risk: "HIGH" })).toBe("NEEDS_REVISION"); });
  it("impide aprobación sin permiso", () => expect(() => decideDemoApproval({ status: "AWAITING_APPROVAL", action: "APPROVE", role: "REPORTERO", risk: "LOW" })).toThrow("permiso"));
});
